### DISCUSSION TITLE
LLM Spacy NER with custom dataset

### DISCUSSION THREAD

**Discussion by Project-NSE** [explosion/spacy-llm#440] [Q&A]
I am working on Named Entity Recognition task using large language model. I used SpaCy for that. I want to build a custom dataset. For testing purpose I created a 2 sentences dataset. The dataset is look like (name of the file ner_example1.yml)

```
- text: "take advil and reduce your fever"
  entities:
    Medicine:
      - advil.
   
- text: "I want to buy tylenol today"
  entities:
    Medicine:
      - tylenol.
```
Now I configure the config.cfg file as required

```
[nlp]
lang = "en"
pipeline = ["llm"]

[components]

[components.llm]
factory = "llm"

[components.llm.task]
@llm_tasks = "spacy.NER.v2"
labels = Medicine

[components.llm.task.examples]
@misc = "spacy.FewShotReader.v1"
path = "ner_examples1.yml"

[components.llm.model]
@llm_models = "spacy.Dolly.v1"
# For better performance, use dolly-v2-12b instead
name = "dolly-v2-3b"
```

The python script to run all those is

```
!python -m pip install spacy-llm
import spacy
from spacy_llm.util import assemble
nlp = assemble("config.cfg")

doc = nlp("Hi Doctor, give me a advil.")

print([(ent.text, ent.label_) for ent in doc.ents])
```

I did not get the proper output for the print statement. It return me an empty array.

It should return [('advil', 'Medicine')]

The output is as follows
![Stackoverflow](https://github.com/explosion/spacy-llm/assets/145517206/0607ad9a-498a-42df-bfd2-a3b140f4cb96)
