### DISCUSSION TITLE
ValueError : The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them.

### DISCUSSION THREAD

**Discussion by NitGS** [explosion/spacy-llm#475] [Q&A]
I tried creating a custom NER model using spacy-llm, but none of my approaches seem to be working. 

I started off by using OpenAI with my API key, but it seemed to be rate-limiting me with no end at sight.
I shifted to other open sources LLMs like OpenLLaMa and Dolly, but they give up too, giving me this error : 

_ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format._

To reproduce this behaviour : 

config.cfg
```
[nlp]
lang = "en"
pipeline = ["llm"]

[components]

[components.llm]
factory = "llm"

[components.llm.task]
@llm_tasks = "spacy.NER.v2"
labels = ACQUIRER, ACQUIREE

[components.llm.task.examples]
@misc = "spacy.FewShotReader.v1"
path = "ner_examples.yml"

[components.llm.model]
@llm_models = "spacy.Dolly.v1"
name = "dolly-v2-3b"
```

ner_examples.yml
```
- text: "ABB acquires stake analytics software company WindESCo"
  entities:
    ACQUIRER:
      - ABB
    ACQUIREE:
      - WindESCo
- text: "US-based technology provider Rocket Software, Inc. has acquired German data integration solutions provider B.O.S., to enhance mainframe modernisation and accelerate hybrid cloud strategies, the company said. "
  entities:
    ACQUIRER:
      - Rocket Software, Inc.
    ACQUIREE:
      - B.O.S.
```

ner.py
```
from spacy_llm.util import assemble
nlp = assemble("config.cfg")

text="""
Tesla has officially acquired Germany-based wireless charging startup, Wiferion, to accelerate the development of its wireless charging platform potentially.
"""
doc = nlp(text)
for e in doc.ents:
    print(e.label_, e.text, e.start, e.end)
```

I need help in figuring out why this error propped up and how to resolve it.

Thanks a lot!!
